version: '2'

networks:
  multiPeers:

services:

  ca.multiPeer:
  image: hyperledger/fabric-ca
  environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca.multiPeer
    - FABRIC_CA_SERVER_CA_CERTIFILE=/etc/hyperledger/fabric-ca-server-config/ca.org.example.com-cert.pem
    - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/
  ports:
    - "7054:7054"
  command: sh -c 'fabric-ca-server start -b admin:adminpw'
  volumes:
    - ./crypto-config/peer0